from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Protocol

from analysis_worker.gemini import GeminiClient
from analysis_worker.payload import AnalysisTaskPayload
from analysis_worker.prompts import (
    build_document_extraction_prompt,
    build_drift_report_prompt,
    build_source_analysis_prompt,
    build_true_design_prompt,
)
from analysis_worker.storage import InputBundle


@dataclass(frozen=True)
class SourceCodeSpecification:
    summary: str
    extracted_items: Dict[str, object]


@dataclass(frozen=True)
class DocumentSpecification:
    summary: str
    extracted_items: Dict[str, object]


@dataclass(frozen=True)
class GeneratedArtifacts:
    true_design_markdown: str
    drift_report_markdown: str

    def as_files(self) -> Dict[str, str]:
        return {
            "true-design.md": self.true_design_markdown,
            "document-drift-report.md": self.drift_report_markdown,
        }


class SourceCodeAnalysisEngine(Protocol):
    def extract(self, payload: AnalysisTaskPayload, inputs: InputBundle) -> SourceCodeSpecification:
        ...


class DocumentExtractionEngine(Protocol):
    def extract(self, payload: AnalysisTaskPayload, inputs: InputBundle) -> DocumentSpecification:
        ...


class TrueDesignGenerator(Protocol):
    def generate(
        self,
        payload: AnalysisTaskPayload,
        source_specification: SourceCodeSpecification,
        document_specification: DocumentSpecification,
    ) -> str:
        ...


class DriftReportGenerator(Protocol):
    def generate(
        self,
        payload: AnalysisTaskPayload,
        source_specification: SourceCodeSpecification,
        document_specification: DocumentSpecification,
    ) -> str:
        ...


class PlaceholderSourceCodeAnalysisEngine:
    def extract(self, payload: AnalysisTaskPayload, inputs: InputBundle) -> SourceCodeSpecification:
        return SourceCodeSpecification(
            summary="Source analysis engine placeholder. Gemini extraction is not implemented yet.",
            extracted_items={
                "source_archive_uri": inputs.source_archive_uri,
                "known_document_count": len(inputs.document_uris),
                "pending_extractors": [
                    "file_structure",
                    "api_routes",
                    "database_definitions",
                    "dependencies",
                    "readme",
                ],
            },
        )


class GeminiSourceCodeAnalysisEngine:
    def __init__(self, gemini_client: GeminiClient) -> None:
        self._gemini_client = gemini_client

    def extract(self, payload: AnalysisTaskPayload, inputs: InputBundle) -> SourceCodeSpecification:
        prompt = build_source_analysis_prompt(payload, inputs)
        response = self._gemini_client.generate(prompt)
        return SourceCodeSpecification(
            summary=response,
            extracted_items={
                "prompt_task": "SOURCE_ANALYSIS",
                "source_archive_uri": inputs.source_archive_uri,
                "source_file_count": len(inputs.source_files),
            },
        )


class PlaceholderDocumentExtractionEngine:
    def extract(self, payload: AnalysisTaskPayload, inputs: InputBundle) -> DocumentSpecification:
        return DocumentSpecification(
            summary="Document extraction engine placeholder. PDF/Excel extraction is not implemented yet.",
            extracted_items={
                "document_uris": list(inputs.document_uris),
                "pending_extractors": ["pdf", "excel", "markdown", "plain_text"],
            },
        )


class GeminiDocumentExtractionEngine:
    def __init__(self, gemini_client: GeminiClient) -> None:
        self._gemini_client = gemini_client

    def extract(self, payload: AnalysisTaskPayload, inputs: InputBundle) -> DocumentSpecification:
        prompt = build_document_extraction_prompt(payload, inputs)
        response = self._gemini_client.generate(prompt)
        return DocumentSpecification(
            summary=response,
            extracted_items={
                "prompt_task": "DOCUMENT_EXTRACTION",
                "document_count": len(inputs.document_uris),
                "document_file_count": len(inputs.document_files),
            },
        )


class PlaceholderTrueDesignGenerator:
    def generate(
        self,
        payload: AnalysisTaskPayload,
        source_specification: SourceCodeSpecification,
        document_specification: DocumentSpecification,
    ) -> str:
        title = payload.project_name or payload.job_id
        lines: List[str] = [
            "# True Design Document",
            "",
            "This is a placeholder artifact generated by the analysis worker skeleton.",
            "It must not be treated as the final implementation-derived design document.",
            "",
            "## Analysis Target",
            "",
            f"- Project: {title}",
            f"- Job ID: {payload.job_id}",
            f"- Source archive: {source_specification.extracted_items.get('source_archive_uri')}",
            f"- Existing documents: {len(document_specification.extracted_items.get('document_uris', []))}",
            "",
            "## Pending Implementation",
            "",
            "- F-02 source code analysis with Gemini API",
            "- F-03 document extraction with Gemini API",
            "- F-04 Markdown design document generation prompt",
        ]
        return "\n".join(lines) + "\n"


class GeminiTrueDesignGenerator:
    def __init__(self, gemini_client: GeminiClient) -> None:
        self._gemini_client = gemini_client

    def generate(
        self,
        payload: AnalysisTaskPayload,
        source_specification: SourceCodeSpecification,
        document_specification: DocumentSpecification,
    ) -> str:
        prompt = build_true_design_prompt(payload, source_specification, document_specification)
        return self._gemini_client.generate(prompt)


class PlaceholderDriftReportGenerator:
    def generate(
        self,
        payload: AnalysisTaskPayload,
        source_specification: SourceCodeSpecification,
        document_specification: DocumentSpecification,
    ) -> str:
        lines = [
            "# Document Drift Report",
            "",
            "This is a placeholder artifact generated by the analysis worker skeleton.",
            "It must not be treated as the final drift analysis report.",
            "",
            "## Summary",
            "",
            "| Category | Count |",
            "| --- | ---: |",
            "| Implemented but undocumented | 0 |",
            "| Documented but not implemented | 0 |",
            "| Content mismatch | 0 |",
            "| Unknown | 0 |",
            "",
            "## Pending Implementation",
            "",
            "- F-05 comparison and four-category classification prompt",
        ]
        return "\n".join(lines) + "\n"


class GeminiDriftReportGenerator:
    def __init__(self, gemini_client: GeminiClient) -> None:
        self._gemini_client = gemini_client

    def generate(
        self,
        payload: AnalysisTaskPayload,
        source_specification: SourceCodeSpecification,
        document_specification: DocumentSpecification,
    ) -> str:
        prompt = build_drift_report_prompt(payload, source_specification, document_specification)
        return self._gemini_client.generate(prompt)
