import path from "node:path";
import { AnalysisTaskPayload } from "./payload.js";
import { AnalysisInput, SpecificationResult } from "./prompts.js";
import { GeminiClient } from "./gemini.js";
import {
  buildDocumentExtractionPrompt,
  buildDriftReportPrompt,
  buildSourceAnalysisPrompt,
  buildTrueDesignPrompt,
} from "./prompts.js";

export interface ExtractionResult extends SpecificationResult {
  extractedItems: Record<string, unknown>;
  debugArtifacts?: Record<string, string>;
}

export interface AnalysisEngine {
  extract(payload: AnalysisTaskPayload, inputs: AnalysisInput): Promise<ExtractionResult>;
}

export class PlaceholderSourceCodeAnalysisEngine implements AnalysisEngine {
  async extract(payload: AnalysisTaskPayload, inputs: AnalysisInput): Promise<ExtractionResult> {
    return {
      summary: "Source analysis engine placeholder. Gemini extraction is not implemented yet.",
      extractedItems: {
        source_archive_uri: inputs.sourceArchiveUri,
        known_document_count: inputs.documentUris.length,
        pending_extractors: [
          "file_structure",
          "api_routes",
          "database_definitions",
          "dependencies",
          "readme",
        ],
      },
    };
  }
}

export class GeminiSourceCodeAnalysisEngine implements AnalysisEngine {
  constructor(private geminiClient: GeminiClient) {}

  async extract(payload: AnalysisTaskPayload, inputs: AnalysisInput): Promise<ExtractionResult> {
    const [overviewMarkdown, overviewItems] = buildSourceCodeOverview(inputs);
    const prompt = buildSourceAnalysisPrompt(payload, inputs, overviewMarkdown);
    const response = await this.geminiClient.generate(prompt);
    const debugArtifacts = buildCodebaseMapDocuments(inputs);
    return {
      summary: joinSections(overviewMarkdown, `## Gemini抽出結果\n\n${response}`),
      extractedItems: {
        prompt_task: "SOURCE_ANALYSIS",
        source_archive_uri: inputs.sourceArchiveUri,
        source_file_count: inputs.sourceFiles.length,
        static_overview: overviewItems,
      },
      debugArtifacts,
    };
  }
}

export class PlaceholderDocumentExtractionEngine implements AnalysisEngine {
  async extract(payload: AnalysisTaskPayload, inputs: AnalysisInput): Promise<ExtractionResult> {
    return {
      summary:
        "Document extraction engine placeholder. PDF/Excel extraction is not implemented yet.",
      extractedItems: {
        document_uris: [...inputs.documentUris],
        pending_extractors: ["pdf", "excel", "markdown", "plain_text"],
      },
    };
  }
}

export class GeminiDocumentExtractionEngine implements AnalysisEngine {
  constructor(private geminiClient: GeminiClient) {}

  async extract(payload: AnalysisTaskPayload, inputs: AnalysisInput): Promise<ExtractionResult> {
    const [overviewMarkdown, overviewItems] = buildDocumentOverview(inputs);
    const prompt = buildDocumentExtractionPrompt(payload, inputs, overviewMarkdown);
    const response = await this.geminiClient.generate(prompt);
    return {
      summary: joinSections(overviewMarkdown, `## Gemini抽出結果\n\n${response}`),
      extractedItems: {
        prompt_task: "DOCUMENT_EXTRACTION",
        document_count: inputs.documentUris.length,
        document_file_count: inputs.documentFiles.length,
        document_overview: overviewItems,
      },
    };
  }
}

export interface DesignGenerator {
  generate(
    payload: AnalysisTaskPayload,
    sourceSpecification: ExtractionResult,
    documentSpecification: ExtractionResult,
  ): Promise<string>;
}

export class PlaceholderTrueDesignGenerator implements DesignGenerator {
  async generate(
    payload: AnalysisTaskPayload,
    sourceSpecification: ExtractionResult,
    documentSpecification: ExtractionResult,
  ): Promise<string> {
    const title = payload.projectName || payload.jobId;
    return [
      "# True Design Document",
      "",
      "This is a placeholder artifact generated by the analysis worker skeleton.",
      "It must not be treated as the final implementation-derived design document.",
      "",
      "## Analysis Target",
      "",
      `- Project: ${title}`,
      `- Job ID: ${payload.jobId}`,
      `- Source archive: ${sourceSpecification.extractedItems.source_archive_uri}`,
      `- Existing documents: ${
        ((documentSpecification.extractedItems.document_uris as string[]) || []).length
      }`,
      "",
      "## Pending Implementation",
      "",
      "- F-02 source code analysis with Gemini API",
      "- F-03 document extraction with Gemini API",
      "- F-04 Markdown design document generation prompt",
      "",
    ].join("\n");
  }
}

export class GeminiTrueDesignGenerator implements DesignGenerator {
  constructor(private geminiClient: GeminiClient) {}

  async generate(
    payload: AnalysisTaskPayload,
    sourceSpecification: ExtractionResult,
    documentSpecification: ExtractionResult,
  ): Promise<string> {
    return this.geminiClient.generate(
      buildTrueDesignPrompt(payload, sourceSpecification, documentSpecification),
    );
  }
}

export class PlaceholderDriftReportGenerator implements DesignGenerator {
  async generate(): Promise<string> {
    return [
      "# Document Drift Report",
      "",
      "This is a placeholder artifact generated by the analysis worker skeleton.",
      "It must not be treated as the final drift analysis report.",
      "",
      "## Summary",
      "",
      "| Category | Count |",
      "| --- | ---: |",
      "| Implemented but undocumented | 0 |",
      "| Documented but not implemented | 0 |",
      "| Content mismatch | 0 |",
      "| Unknown | 0 |",
      "",
      "## Pending Implementation",
      "",
      "- F-05 comparison and four-category classification prompt",
      "",
    ].join("\n");
  }
}

export class GeminiDriftReportGenerator implements DesignGenerator {
  constructor(private geminiClient: GeminiClient) {}

  async generate(
    payload: AnalysisTaskPayload,
    sourceSpecification: ExtractionResult,
    documentSpecification: ExtractionResult,
  ): Promise<string> {
    return this.geminiClient.generate(
      buildDriftReportPrompt(payload, sourceSpecification, documentSpecification),
    );
  }
}

export function generatedArtifacts(trueDesignMarkdown: string, driftReportMarkdown: string) {
  return {
    trueDesignMarkdown,
    driftReportMarkdown,
    asFiles() {
      return {
        "true-design.md": this.trueDesignMarkdown,
        "document-drift-report.md": this.driftReportMarkdown,
      };
    },
  };
}

export function buildSourceCodeOverview(inputs: AnalysisInput): [string, Record<string, unknown>] {
  const analysisFiles = inputs.allSourceFiles && inputs.allSourceFiles.length > 0 ? inputs.allSourceFiles : inputs.sourceFiles;
  const filePaths = analysisFiles.map((file) => file.path);
  const dependencies = collectDependencies(analysisFiles);
  const apiRoutes = collectApiRoutes(analysisFiles);
  const databaseDefinitions = collectDatabaseDefinitions(analysisFiles);
  const configFiles = filePaths.filter((filePath) => isConfigFile(filePath));
  const readmeFiles = filePaths.filter((filePath) =>
    path.basename(filePath).toLowerCase().startsWith("readme"),
  );
  const directoryTree = buildDirectoryTree(filePaths);
  const moduleDependencyGraph = buildModuleDependencyGraph(analysisFiles);
  const iacStructureMap = buildIaCStructureMap(analysisFiles);

  const items = {
    file_structure: filePaths,
    dependencies,
    api_routes: apiRoutes,
    database_definitions: databaseDefinitions,
    config_files: configFiles,
    readme_files: readmeFiles,
  };

  const lines = [
    "## 静的構造解析結果",
    "",
    "### ディレクトリ構造",
    "",
    directoryTree || "ソースファイルはありません。",
    "",
    "### 設定ファイル",
    "",
    ...formatBullets(configFiles, "設定ファイル候補は検出されませんでした。"),
    "",
    "### README",
    "",
    ...formatBullets(readmeFiles, "README候補は検出されませんでした。"),
    "",
    "### 依存関係",
    "",
    ...formatDependencyTable(dependencies),
    "",
    "### ルーティング/API候補",
    "",
    ...formatRouteTable(apiRoutes),
    "",
    "### DB定義/データモデル候補",
    "",
    ...formatDatabaseTable(databaseDefinitions),
    "",
    "### モジュール間依存グラフ",
    "",
    moduleDependencyGraph,
    "",
    "### IaC構成要素",
    "",
    iacStructureMap,
  ];
  return [lines.join("\n"), items];
}

/**
 * 静的解析の中間成果物を複数ファイルに分割して返す。
 *
 * - codebase-map.md         : ディレクトリツリー＋サービス境界（人間可読）
 * - codebase-map.json       : サービス境界・エントリポイント付きの構造化 JSON
 * - module-dependencies.mmd : Mermaid 生構文（コードブロックなし、上限なし）
 * - iac-structure.md        : IaC 構成要素＋DynamoDB スキーマ＋Lambda 設定
 * - api-spec.yaml           : OpenAPI/api-spec ファイル（存在すれば）
 * - exported-symbols.md     : サービス別エクスポートシンボル一覧
 */
export function buildCodebaseMapDocuments(inputs: AnalysisInput): Record<string, string> {
  const analysisFiles =
    inputs.allSourceFiles && inputs.allSourceFiles.length > 0
      ? inputs.allSourceFiles
      : inputs.sourceFiles;
  const filePaths = analysisFiles.map((file) => file.path);
  const directoryTree = buildDirectoryTree(filePaths);
  const mermaidRaw = buildModuleDependencyMermaid(analysisFiles);
  const iacStructureMd = buildIaCStructureMap(analysisFiles);
  const serviceBoundaries = detectServiceBoundaries(filePaths);
  const exportedSymbolsMd = buildExportedSymbolsDocument(analysisFiles, serviceBoundaries);
  const apiSpecFiles = extractApiSpecFiles(analysisFiles);

  // --- codebase-map.md ---
  const servicesSummary = Object.entries(serviceBoundaries)
    .map(([name, info]) => [
      `### ${name}`,
      `- タイプ: ${info.type}`,
      `- エントリポイント: ${info.entrypoint ?? "不明"}`,
      `- ファイル数: ${info.files.length}`,
    ].join("\n"))
    .join("\n\n");

  const codebaseMapMd = [
    "# コードベースマップ（静的解析結果）",
    "",
    "> このファイルは analysis-worker の静的解析フェーズで自動生成されたデバッグ用中間成果物です。",
    "> Gemini による解析結果ではなく、正規表現ベースの構造抽出結果を示します。",
    "",
    "---",
    "",
    "## サービス境界",
    "",
    servicesSummary || "サービス境界は検出されませんでした。",
    "",
    "---",
    "",
    "## ディレクトリ構造",
    "",
    directoryTree || "ソースファイルはありません。",
    "",
    "---",
    "",
    "## 統計",
    "",
    `- 総ファイル数: ${filePaths.length}`,
    `- サービス数: ${Object.keys(serviceBoundaries).length}`,
  ].join("\n");

  // --- codebase-map.json ---
  const codebaseMapJson = JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      totalFiles: filePaths.length,
      services: serviceBoundaries,
      files: filePaths,
    },
    null,
    2,
  );

  const result: Record<string, string> = {
    "codebase-map.md": codebaseMapMd,
    "codebase-map.json": codebaseMapJson,
    "module-dependencies.mmd": mermaidRaw,
    "iac-structure.md": iacStructureMd,
    "exported-symbols.md": exportedSymbolsMd,
  };

  // api-spec ファイルが見つかれば追加
  for (const [name, content] of Object.entries(apiSpecFiles)) {
    result[name] = content;
  }

  return result;
}

/**
 * @deprecated buildCodebaseMapDocuments を使用してください。
 * 後方互換のため残します。
 */
export function buildSourceCodeMapDocument(inputs: AnalysisInput): string {
  const docs = buildCodebaseMapDocuments(inputs);
  return docs["codebase-map.md"];
}

/**
 * ファイルパス一覧からASCIIディレクトリツリーを生成する。
 *
 * @example
 * buildDirectoryTree(["src/index.ts", "src/engines.ts", "README.md"])
 * // => "README.md\nsrc/\n├── engines.ts\n└── index.ts"
 */
export function buildDirectoryTree(filePaths: string[]): string {
  if (filePaths.length === 0) {
    return "";
  }

  // パスをUnix区切りに正規化
  const normalized = filePaths.map((p) => p.replaceAll("\\", "/"));

  // ツリー構造をネストしたMapで構築: Map<name, subtree>
  type Tree = Map<string, Tree>;
  const root: Tree = new Map();

  for (const filePath of normalized) {
    const parts = filePath.split("/");
    let node = root;
    for (const part of parts) {
      if (!node.has(part)) {
        node.set(part, new Map());
      }
      node = node.get(part)!;
    }
  }

  function renderTree(node: Tree, prefix: string): string[] {
    const entries = [...node.entries()].sort(([a, aNode], [b, bNode]) => {
      // ディレクトリを先にソート
      const aIsDir = aNode.size > 0;
      const bIsDir = bNode.size > 0;
      if (aIsDir !== bIsDir) return aIsDir ? -1 : 1;
      return a.localeCompare(b);
    });
    const lines: string[] = [];
    entries.forEach(([name, subtree], index) => {
      const isLast = index === entries.length - 1;
      const connector = isLast ? "└── " : "├── ";
      const childPrefix = isLast ? prefix + "    " : prefix + "│   ";
      if (subtree.size > 0) {
        lines.push(`${prefix}${connector}${name}/`);
        lines.push(...renderTree(subtree, childPrefix));
      } else {
        lines.push(`${prefix}${connector}${name}`);
      }
    });
    return lines;
  }

  return renderTree(root, "").join("\n");
}

const MAX_DEPENDENCY_EDGES = 50;

/**
 * ソースファイルのimport文を静的解析し、Mermaid形式のモジュール依存グラフを生成する。
 * 相対パスimportのみを対象とし、外部パッケージは除外する。
 * 最大MAX_DEPENDENCY_EDGES件のエッジに制限する。
 */
export function buildModuleDependencyGraph(
  files: Array<{ path: string; content: string }>,
): string {
  // (path without extension) => node alias (e.g. "n1")
  const nodeAliasMap = new Map<string, string>();
  let nodeCounter = 0;

  function getAlias(normalizedPath: string): string {
    if (!nodeAliasMap.has(normalizedPath)) {
      nodeCounter++;
      nodeAliasMap.set(normalizedPath, `n${nodeCounter}`);
    }
    return nodeAliasMap.get(normalizedPath)!;
  }

  /**
   * ファイルパスから拡張子を除去してノードキーに使う。
   * import 先は拡張子なしで書かれることが多いため、
   * from 側（拡張子あり）と to 側（拡張子なし）を同一ノードに統一する。
   */
  function stripExtension(filePath: string): string {
    const jstsExts = /\.(js|jsx|ts|tsx|mjs|cjs)$/i;
    return filePath.replace(jstsExts, "");
  }

  const edgeSet = new Set<string>(); // 重複排除用
  const edges: Array<{ fromKey: string; toKey: string }> = [];

  for (const file of files) {
    if (edges.length >= MAX_DEPENDENCY_EDGES) break;
    if (isTestFile(file.path)) continue;

    const ext = file.path.split(".").pop()?.toLowerCase() ?? "";
    const isJsTs = ["js", "jsx", "ts", "tsx", "mjs", "cjs"].includes(ext);
    const isPython = ext === "py";

    const importPaths: string[] = [];

    if (isJsTs) {
      // ES module: import ... from './foo'
      for (const match of file.content.matchAll(
        /^import\s+[\s\S]*?from\s+['"]([^'"]+)['"]/gm,
      )) {
        importPaths.push(match[1]);
      }
      // dynamic import: import('./foo') / require('./foo')
      for (const match of file.content.matchAll(
        /(?:import|require)\s*\(\s*['"]([^'"]+)['"]\s*\)/gm,
      )) {
        importPaths.push(match[1]);
      }
      // CommonJS: const x = require('./foo')
      for (const match of file.content.matchAll(
        /require\s*\(\s*['"]([^'"]+)['"]\s*\)/gm,
      )) {
        importPaths.push(match[1]);
      }
    }

    if (isPython) {
      // from .foo import bar
      for (const match of file.content.matchAll(
        /^from\s+(\.+[\w./]*)\s+import/gm,
      )) {
        importPaths.push(match[1]);
      }
      // import .foo  (relative import)
      for (const match of file.content.matchAll(/^import\s+(\.+[\w.]+)/gm)) {
        importPaths.push(match[1]);
      }
    }

    for (const importPath of importPaths) {
      // 相対パスのみ対象
      if (!importPath.startsWith(".")) continue;

      const fromDir = file.path.includes("/")
        ? file.path.slice(0, file.path.lastIndexOf("/"))
        : "";
      const resolvedRaw = fromDir ? `${fromDir}/${importPath}` : importPath;
      // 簡易パス正規化（../を解決）
      const resolved = resolveRelativePath(resolvedRaw);

      // from は実ファイルパスから拡張子除去、to はimport先（元々拡張子なしが多い）から拡張子除去
      // →両者を同じキー空間で扱い、同一ノードに収束させる
      const fromKey = stripExtension(file.path);
      const toKey = stripExtension(resolved);

      if (!fromKey || !toKey || fromKey === toKey) continue;

      // 重複エッジを除去
      const edgeId = `${fromKey}\0${toKey}`;
      if (edgeSet.has(edgeId)) continue;
      edgeSet.add(edgeId);

      edges.push({ fromKey, toKey });
      if (edges.length >= MAX_DEPENDENCY_EDGES) break;
    }
  }

  if (edges.length === 0) {
    return "モジュール間の相対import依存は検出されませんでした。";
  }

  // 全エッジに登場するノードのエイリアスを確定
  for (const { fromKey, toKey } of edges) {
    getAlias(fromKey);
    getAlias(toKey);
  }

  // ノード宣言行: n1["path/to/file"] 形式（ダブルクォートをエスケープ）
  const nodeDefs = [...nodeAliasMap.entries()].map(
    ([label, alias]) => `  ${alias}["${label.replace(/"/g, "#quot;")}"]`,
  );

  const edgeLines = edges.map(
    ({ fromKey, toKey }) => `  ${getAlias(fromKey)} --> ${getAlias(toKey)}`,
  );

  const truncated = edges.length >= MAX_DEPENDENCY_EDGES;
  const lines = [
    "```mermaid",
    "graph TD",
    ...nodeDefs,
    "",
    ...edgeLines,
    "```",
  ];
  if (truncated) {
    lines.push("");
    lines.push(`> ※ エッジ数が上限（${MAX_DEPENDENCY_EDGES}件）に達したため、一部を省略しています。`);
  }
  return lines.join("\n");
}

/**
 * 解析対象外ファイルかどうかを判定する。
 * テスト・Storybook・Playwright・プロファイル JSON・ロックファイル等を除外する。
 */
function isAnalysisTarget(filePath: string): boolean {
  if (isTestFile(filePath)) return false;
  const normalized = filePath.replaceAll("\\", "/").toLowerCase();
  const excludedDirs = [
    "/.storybook/",
    "/playwright/",
    "/profile/",
    "/debug/",
    "/generated/",
    "/node_modules/",
    "/dist/",
    "/.github/",
    "/.vscode/",
  ];
  if (excludedDirs.some((d) => normalized.includes(d))) return false;
  const basename = normalized.split("/").at(-1) ?? "";
  if ([
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "go.sum",
    ".gitignore",
    ".prettierrc",
    ".eslintrc.js",
    "jest.config.js",
    "vitest.config.ts",
    "tsconfig.json",
  ].includes(basename)) return false;
  return true;
}

/**
 * Mermaid 形式のモジュール依存グラフを生構文（コードブロックなし）で返す。
 * .mmd ファイルへの直接書き出しに使用する。
 * エッジ上限なし・解析対象外ファイルを除外する。
 */
export function buildModuleDependencyMermaid(
  files: Array<{ path: string; content: string }>,
): string {
  // (path without extension) => node alias (e.g. "n1")
  const nodeAliasMap = new Map<string, string>();
  let nodeCounter = 0;

  function getAlias(normalizedPath: string): string {
    if (!nodeAliasMap.has(normalizedPath)) {
      nodeCounter++;
      nodeAliasMap.set(normalizedPath, `n${nodeCounter}`);
    }
    return nodeAliasMap.get(normalizedPath)!;
  }

  function stripExtension(filePath: string): string {
    const jstsExts = /\.(js|jsx|ts|tsx|mjs|cjs)$/i;
    return filePath.replace(jstsExts, "");
  }

  const edgeSet = new Set<string>();
  const edges: Array<{ fromKey: string; toKey: string }> = [];

  for (const file of files) {
    // 解析対象外ファイルを除外（テスト・Storybook・Playwright等）
    if (!isAnalysisTarget(file.path)) continue;

    const ext = file.path.split(".").pop()?.toLowerCase() ?? "";
    const isJsTs = ["js", "jsx", "ts", "tsx", "mjs", "cjs"].includes(ext);
    const isPython = ext === "py";
    const importPaths: string[] = [];

    if (isJsTs) {
      for (const match of file.content.matchAll(
        /^import\s+[\s\S]*?from\s+['"]([^'"]+)['"]/gm,
      )) {
        importPaths.push(match[1]);
      }
      for (const match of file.content.matchAll(
        /(?:import|require)\s*\(\s*['"]([^'"]+)['"]\s*\)/gm,
      )) {
        importPaths.push(match[1]);
      }
      for (const match of file.content.matchAll(
        /require\s*\(\s*['"]([^'"]+)['"]\s*\)/gm,
      )) {
        importPaths.push(match[1]);
      }
    }

    if (isPython) {
      for (const match of file.content.matchAll(
        /^from\s+(\.+[\w./]*)\s+import/gm,
      )) {
        importPaths.push(match[1]);
      }
      for (const match of file.content.matchAll(/^import\s+(\.+[\w.]+)/gm)) {
        importPaths.push(match[1]);
      }
    }

    for (const importPath of importPaths) {
      if (!importPath.startsWith(".")) continue;
      const fromDir = file.path.includes("/")
        ? file.path.slice(0, file.path.lastIndexOf("/"))
        : "";
      const resolvedRaw = fromDir ? `${fromDir}/${importPath}` : importPath;
      const resolved = resolveRelativePath(resolvedRaw);
      const fromKey = stripExtension(file.path);
      const toKey = stripExtension(resolved);
      if (!fromKey || !toKey || fromKey === toKey) continue;
      const edgeId = `${fromKey}\0${toKey}`;
      if (edgeSet.has(edgeId)) continue;
      edgeSet.add(edgeId);
      edges.push({ fromKey, toKey });
    }
  }

  if (edges.length === 0) {
    return "%% モジュール間の相対import依存は検出されませんでした。";
  }

  for (const { fromKey, toKey } of edges) {
    getAlias(fromKey);
    getAlias(toKey);
  }

  const nodeDefs = [...nodeAliasMap.entries()].map(
    ([label, alias]) => `  ${alias}["${label.replace(/"/g, "#quot;")}"]`,
  );
  const edgeLines = edges.map(
    ({ fromKey, toKey }) => `  ${getAlias(fromKey)} --> ${getAlias(toKey)}`,
  );

  return ["graph TD", ...nodeDefs, "", ...edgeLines].join("\n");
}

/**
 * 各種IaCファイル（Terraform, AWS CDK, CloudFormation/SAM, Kubernetes等）を静的解析し、
 * 構成要素・DynamoDB スキーマ・Lambda 設定を含む詳細 Markdown を返す。
 */
export function buildIaCStructureMap(
  files: Array<{ path: string; content: string }>,
): string {
  interface IaCItem {
    kind: string;
    name: string;
    path: string;
    details?: string; // 追加プロパティ（スキーマ、設定値等）
  }

  interface DynamoDBTable {
    logicalName: string;
    tableName?: string;
    pk?: string;
    sk?: string;
    gsi: string[];
    billingMode?: string;
    path: string;
  }

  interface LambdaFunction {
    logicalName: string;
    handler?: string;
    runtime?: string;
    envVars: Record<string, string>;
    policies: string[];
    path: string;
  }

  const items: IaCItem[] = [];
  const dynamoTables: DynamoDBTable[] = [];
  const lambdaFunctions: LambdaFunction[] = [];

  for (const file of files) {
    if (isTestFile(file.path)) continue;

    const ext = file.path.split(".").pop()?.toLowerCase() ?? "";

    // 1. Terraform (.tf)
    if (ext === "tf") {
      for (const line of file.content.split(/\r?\n/)) {
        const stripped = line.trim();
        const providerMatch = stripped.match(/^provider\s+"([^"]+)"/);
        if (providerMatch) {
          items.push({ kind: "provider", name: providerMatch[1], path: file.path });
          continue;
        }
        const resourceMatch = stripped.match(/^resource\s+"([^"]+)"\s+"([^"]+)"/);
        if (resourceMatch) {
          items.push({
            kind: "resource",
            name: `${resourceMatch[1]}.${resourceMatch[2]}`,
            path: file.path,
          });
          continue;
        }
        const moduleMatch = stripped.match(/^module\s+"([^"]+)"/);
        if (moduleMatch) {
          items.push({ kind: "module", name: moduleMatch[1], path: file.path });
          continue;
        }
        const variableMatch = stripped.match(/^variable\s+"([^"]+)"/);
        if (variableMatch) {
          items.push({ kind: "variable", name: variableMatch[1], path: file.path });
          continue;
        }
        const outputMatch = stripped.match(/^output\s+"([^"]+)"/);
        if (outputMatch) {
          items.push({ kind: "output", name: outputMatch[1], path: file.path });
          continue;
        }
      }
      continue;
    }

    // 2. AWS CDK (TypeScript / JavaScript)
    if (ext === "ts" || ext === "js" || ext === "tsx" || ext === "jsx") {
      const normalizedPath = file.path.replaceAll("\\", "/");
      const isCdkPath = normalizedPath.includes("/cdk/") || normalizedPath.includes("cdk/");
      const hasCdkImport =
        file.content.includes("aws-cdk-lib") ||
        file.content.includes("@aws-cdk") ||
        file.content.includes("constructs");

      if (isCdkPath || hasCdkImport) {
        const classMatches = file.content.matchAll(
          /class\s+([a-zA-Z0-9_$]+)\s+extends\s+(?:[a-zA-Z0-9_$]+\.)?(Stack|Construct|Resource)\b/g,
        );
        for (const match of classMatches) {
          items.push({ kind: `CDK ${match[2]}`, name: match[1], path: file.path });
        }
        const excludeClassNames = new Set([
          "App", "Stack", "Construct", "Error", "Date", "Map", "Set", "Promise",
          "RegExp", "Object", "Array", "String", "Number", "Boolean",
          "CanonicalUserPrincipal", "ArnPrincipal", "ServicePrincipal",
          "AccountRootPrincipal", "AnyPrincipal", "PolicyStatement",
        ]);
        const newMatches = file.content.matchAll(
          /new\s+([a-zA-Z0-9_$]+\.[a-zA-Z0-9_$]+|[A-Z][a-zA-Z0-9_$]+)\s*\(/g,
        );
        for (const match of newMatches) {
          const className = match[1];
          const shortName = className.includes(".") ? className.split(".").pop()! : className;
          if (excludeClassNames.has(className) || excludeClassNames.has(shortName)) continue;
          items.push({ kind: "CDK Resource", name: className, path: file.path });
        }
      }
      continue;
    }

    // 3. CloudFormation / SAM (.yaml, .yml, .json)
    if ((ext === "yaml" || ext === "yml" || ext === "json") &&
        file.content.includes("AWSTemplateFormatVersion")) {
      const cfnLines = file.content.split(/\r?\n/);

      // リソースブロックを行単位でスキャン
      for (let i = 0; i < cfnLines.length; i++) {
        const line = cfnLines[i];
        const typeMatch = line.match(/^(\s*)Type:\s*['"]?(AWS::[a-zA-Z0-9::]+)['"]?/);
        if (!typeMatch) continue;

        const typeIndent = typeMatch[1].length;
        const resType = typeMatch[2];

        // リソース論理名を逆探索
        let resName = "Unknown";
        for (let j = i - 1; j >= 0; j--) {
          const nm = cfnLines[j].match(/^(\s*)([a-zA-Z0-9_-]+):\s*$/);
          if (nm && nm[1].length < typeIndent) { resName = nm[2]; break; }
        }

        items.push({
          kind: "CloudFormation Resource",
          name: `${resName} (${resType})`,
          path: file.path,
        });

        // --- DynamoDB テーブルの詳細抽出 ---
        if (resType === "AWS::DynamoDB::Table") {
          const table: DynamoDBTable = { logicalName: resName, path: file.path, gsi: [] };
          // Properties ブロックを収集（次のトップレベルキーまで）
          const propStart = i + 1;
          let propEnd = cfnLines.length;
          for (let k = propStart; k < cfnLines.length; k++) {
            if (cfnLines[k].match(/^(\s{0,2})\w/) && k > propStart) { propEnd = k; break; }
          }
          const propBlock = cfnLines.slice(propStart, propEnd).join("\n");
          const tnMatch = propBlock.match(/TableName:\s*['"]?([\w-]+)['"]?/);
          if (tnMatch) table.tableName = tnMatch[1];
          const bmMatch = propBlock.match(/BillingMode:\s*([\w_]+)/);
          if (bmMatch) table.billingMode = bmMatch[1];
          // KeySchema
          for (const ks of propBlock.matchAll(/AttributeName:\s*([\w-]+)[\s\S]*?KeyType:\s*(HASH|RANGE)/g)) {
            if (ks[2] === "HASH") table.pk = ks[1];
            else table.sk = ks[1];
          }
          // GSI
          for (const gsi of propBlock.matchAll(/IndexName:\s*['"]?([\w-]+)['"]?/g)) {
            table.gsi.push(gsi[1]);
          }
          dynamoTables.push(table);
        }

        // --- Lambda 関数の詳細抽出 ---
        if (resType === "AWS::Lambda::Function" || resType === "AWS::Serverless::Function") {
          const fn: LambdaFunction = { logicalName: resName, path: file.path, envVars: {}, policies: [] };
          const propStart2 = i + 1;
          let propEnd2 = cfnLines.length;
          for (let k = propStart2; k < cfnLines.length; k++) {
            if (cfnLines[k].match(/^(\s{0,2})\w/) && k > propStart2) { propEnd2 = k; break; }
          }
          const propBlock2 = cfnLines.slice(propStart2, propEnd2).join("\n");
          const hMatch = propBlock2.match(/Handler:\s*([\w./:-]+)/);
          if (hMatch) fn.handler = hMatch[1];
          const rtMatch = propBlock2.match(/Runtime:\s*([\w.]+)/);
          if (rtMatch) fn.runtime = rtMatch[1];
          // 環境変数
          const envBlock = propBlock2.match(/Variables:([\s\S]*?)(?:\n\s{0,6}\w|$)/);
          if (envBlock) {
            for (const ev of envBlock[1].matchAll(/([A-Z_][A-Z0-9_]*):\s*(.+)/g)) {
              fn.envVars[ev[1]] = ev[2].trim().slice(0, 80);
            }
          }
          // ポリシー
          for (const pol of propBlock2.matchAll(/(?:PolicyName|ManagedPolicyArn|PolicyArn):\s*['"]?([\w:/.-]+)['"]?/g)) {
            fn.policies.push(pol[1]);
          }
          lambdaFunctions.push(fn);
        }
      }
      continue;
    }

    // 4. Kubernetes (.yaml, .yml)
    if ((ext === "yaml" || ext === "yml") &&
        file.content.includes("apiVersion:") && file.content.includes("kind:")) {
      let kind = "";
      let name = "";
      for (const line of file.content.split(/\r?\n/)) {
        if (!kind) { const m = line.match(/^\s*kind:\s*([a-zA-Z0-9_-]+)/); if (m) kind = m[1]; }
        if (!name) { const m = line.match(/^\s*name:\s*([a-zA-Z0-9_-]+)/); if (m) name = m[1]; }
      }
      if (kind && name) items.push({ kind: `Kubernetes ${kind}`, name, path: file.path });
      continue;
    }
  }

  // 重複排除
  const seen = new Set<string>();
  const uniqueItems: IaCItem[] = [];
  for (const item of items) {
    const key = `${item.kind}|${item.name}|${item.path}`;
    if (!seen.has(key)) { seen.add(key); uniqueItems.push(item); }
  }

  const sections: string[] = [
    "# IaC構成要素（静的解析結果）",
    "",
    "> このファイルは analysis-worker の静的解析フェーズで自動生成されたデバッグ用中間成果物です。",
    "> Terraform / AWS CDK / CloudFormation / SAM / Kubernetes を対象に正規表現で抽出した構成要素を示します。",
    "",
  ];

  // --- DynamoDB スキーマセクション ---
  if (dynamoTables.length > 0) {
    sections.push("## DynamoDB テーブルスキーマ", "");
    for (const t of dynamoTables) {
      sections.push(`### ${t.logicalName}${t.tableName ? ` (TableName: ${t.tableName})` : ""}`);
      sections.push(`- ファイル: ${t.path}`);
      if (t.pk) sections.push(`- PK (HASH): \`${t.pk}\``);
      if (t.sk) sections.push(`- SK (RANGE): \`${t.sk}\``);
      if (t.billingMode) sections.push(`- BillingMode: ${t.billingMode}`);
      if (t.gsi.length > 0) sections.push(`- GSI: ${t.gsi.join(", ")}`);
      sections.push("");
    }
  }

  // --- Lambda 設定セクション ---
  if (lambdaFunctions.length > 0) {
    sections.push("## Lambda / Serverless 関数設定", "");
    for (const fn of lambdaFunctions) {
      sections.push(`### ${fn.logicalName}`);
      sections.push(`- ファイル: ${fn.path}`);
      if (fn.handler) sections.push(`- Handler: \`${fn.handler}\``);
      if (fn.runtime) sections.push(`- Runtime: ${fn.runtime}`);
      if (Object.keys(fn.envVars).length > 0) {
        sections.push("- 環境変数:");
        for (const [k, v] of Object.entries(fn.envVars)) {
          sections.push(`  - \`${k}\`: ${v}`);
        }
      }
      if (fn.policies.length > 0) sections.push(`- Policies: ${fn.policies.join(", ")}`);
      sections.push("");
    }
  }

  // --- リソース一覧テーブル ---
  sections.push("## リソース一覧", "");
  if (uniqueItems.length === 0) {
    sections.push("IaC構成要素は検出されませんでした。");
  } else {
    sections.push(
      "| 種別 | 名前 | ファイル |",
      "| --- | --- | --- |",
      ...uniqueItems.map((item) => `| ${item.kind} | ${item.name} | ${item.path} |`),
    );
  }

  return sections.join("\n");
}

/**
 * サービス境界を検出する。
 * `services/xxx/` パターンを基準にサービスをグループ化し、エントリポイントを特定する。
 */
export function detectServiceBoundaries(
  filePaths: string[],
): Record<string, { type: string; entrypoint: string | null; files: string[] }> {
  const services: Record<string, { type: string; entrypoint: string | null; files: string[] }> = {};

  const ENTRY_PATTERNS = ["lambda.ts", "lambda.js", "server.ts", "server.js", "main.ts", "main.js", "index.ts", "index.js", "app.ts", "app.js"];
  const FRONTEND_SIGNALS = ["src/routes/", "src/pages/", "src/App.", "public/index.html"];
  const BACKEND_SIGNALS = ["/lambda.", "/server.", "/handler."];

  for (const filePath of filePaths) {
    const normalized = filePath.replaceAll("\\", "/");

    // services/xxx/ パターン
    const svcMatch = normalized.match(/(?:^|\/)services\/([^/]+)\//);
    if (svcMatch) {
      const svcName = svcMatch[1];
      if (!services[svcName]) {
        services[svcName] = { type: "unknown", entrypoint: null, files: [] };
      }
      services[svcName].files.push(filePath);

      // タイプ推定
      if (FRONTEND_SIGNALS.some((s) => normalized.includes(s))) {
        services[svcName].type = "frontend_spa";
      } else if (BACKEND_SIGNALS.some((s) => normalized.includes(s))) {
        services[svcName].type = "backend_api";
      } else if (normalized.includes("/infra/") || normalized.includes("/cdk/")) {
        services[svcName].type = "infrastructure";
      }

      // エントリポイント候補
      const basename = normalized.split("/").at(-1) ?? "";
      if (!services[svcName].entrypoint && ENTRY_PATTERNS.includes(basename)) {
        services[svcName].entrypoint = filePath;
      }
      continue;
    }

    // infrastructures/ / infra/ トップレベルディレクトリ
    const infraMatch = normalized.match(/(?:^|\/)(?:infrastructures|infra)\/([^/]+)\//);
    if (infraMatch) {
      const infraName = `infra/${infraMatch[1]}`;
      if (!services[infraName]) {
        services[infraName] = { type: "infrastructure", entrypoint: null, files: [] };
      }
      services[infraName].files.push(filePath);
    }
  }

  return services;
}

/**
 * OpenAPI / api-spec ファイルを検索してファイル名→内容のマップで返す。
 * API エージェントがそのまま参照できる形式で出力する。
 */
export function extractApiSpecFiles(
  files: Array<{ path: string; content: string }>,
): Record<string, string> {
  const result: Record<string, string> = {};

  const API_SPEC_NAMES = [
    "api-spec.yaml", "api-spec.yml", "api-spec.json",
    "openapi.yaml", "openapi.yml", "openapi.json",
    "swagger.yaml", "swagger.yml", "swagger.json",
  ];

  for (const file of files) {
    const basename = file.path.replaceAll("\\", "/").split("/").at(-1)?.toLowerCase() ?? "";
    if (API_SPEC_NAMES.includes(basename)) {
      // 出力キーはベース名のみ（複数ある場合はパスを含める）
      const key = result[basename] !== undefined
        ? `api-spec-${file.path.replaceAll("/", "-").replaceAll("\\", "-")}`
        : basename;
      result[key] = file.content;
    }
  }

  return result;
}

/**
 * サービス別にエクスポートシンボル（関数・クラス・型・定数）を抽出し Markdown で返す。
 * API エージェントと BL エージェントが「どのファイルが何を提供するか」を把握するためのファイル。
 */
export function buildExportedSymbolsDocument(
  files: Array<{ path: string; content: string }>,
  services: Record<string, { type: string; entrypoint: string | null; files: string[] }>,
): string {
  interface Symbol {
    kind: string;
    name: string;
    file: string;
  }

  const symbolsByService: Record<string, Symbol[]> = {};
  const ungrouped: Symbol[] = [];

  // ファイル→サービス のルックアップ
  const fileToService = new Map<string, string>();
  for (const [svcName, info] of Object.entries(services)) {
    for (const f of info.files) fileToService.set(f, svcName);
  }

  const EXPORT_PATTERNS: Array<{ re: RegExp; kind: string }> = [
    { re: /^export\s+(?:async\s+)?function\s+([a-zA-Z_$][a-zA-Z0-9_$]*)/m, kind: "function" },
    { re: /^export\s+class\s+([a-zA-Z_$][a-zA-Z0-9_$]*)/m, kind: "class" },
    { re: /^export\s+(?:abstract\s+)?class\s+([a-zA-Z_$][a-zA-Z0-9_$]*)/m, kind: "class" },
    { re: /^export\s+interface\s+([a-zA-Z_$][a-zA-Z0-9_$]*)/m, kind: "interface" },
    { re: /^export\s+type\s+([a-zA-Z_$][a-zA-Z0-9_$]*)\s*=/m, kind: "type" },
    { re: /^export\s+(?:const|let|var)\s+([a-zA-Z_$][a-zA-Z0-9_$]*)/m, kind: "const" },
    { re: /^export\s+enum\s+([a-zA-Z_$][a-zA-Z0-9_$]*)/m, kind: "enum" },
    { re: /^export\s+default\s+(?:function|class)\s+([a-zA-Z_$][a-zA-Z0-9_$]*)/m, kind: "default" },
  ];

  for (const file of files) {
    if (!isAnalysisTarget(file.path)) continue;
    const ext = file.path.split(".").pop()?.toLowerCase() ?? "";
    if (!["ts", "tsx", "js", "jsx", "mjs"].includes(ext)) continue;

    const foundSymbols: Symbol[] = [];
    const lines = file.content.split(/\r?\n/);

    for (const line of lines) {
      const stripped = line.trim();
      for (const { re, kind } of EXPORT_PATTERNS) {
        const m = stripped.match(re);
        if (m && m[1]) {
          // 重複チェック
          if (!foundSymbols.some((s) => s.name === m[1] && s.kind === kind)) {
            foundSymbols.push({ kind, name: m[1], file: file.path });
          }
          break;
        }
      }
    }

    if (foundSymbols.length === 0) continue;

    const svcName = fileToService.get(file.path);
    if (svcName) {
      if (!symbolsByService[svcName]) symbolsByService[svcName] = [];
      symbolsByService[svcName].push(...foundSymbols);
    } else {
      ungrouped.push(...foundSymbols);
    }
  }

  const lines: string[] = [
    "# エクスポートシンボル一覧（静的解析結果）",
    "",
    "> このファイルは analysis-worker の静的解析フェーズで自動生成されたデバッグ用中間成果物です。",
    "> TypeScript/JavaScript ファイルのエクスポートシンボルを正規表現で抽出しています。",
    "",
    "---",
    "",
  ];

  const allGroups: Array<[string, Symbol[]]> = [
    ...Object.entries(symbolsByService),
    ...(ungrouped.length > 0 ? [["(未分類)", ungrouped] as [string, Symbol[]]] : []),
  ];

  if (allGroups.length === 0) {
    lines.push("エクスポートシンボルは検出されませんでした。");
    return lines.join("\n");
  }

  for (const [svcName, symbols] of allGroups) {
    lines.push(`## ${svcName}`, "");
    lines.push(
      "| 種別 | シンボル名 | ファイル |",
      "| --- | --- | --- |",
      ...symbols.map((s) => `| ${s.kind} | \`${s.name}\` | ${s.file} |`),
    );
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * 相対パスを簡易正規化する（../を解決）。
 */
function resolveRelativePath(rawPath: string): string {
  const parts = rawPath.split("/");
  const resolved: string[] = [];
  for (const part of parts) {
    if (part === "..") {
      resolved.pop();
    } else if (part !== ".") {
      resolved.push(part);
    }
  }
  return resolved.join("/");
}

// sanitizeMermaidLabel は buildModuleDependencyGraph 内の stripExtension / getAlias に統合されたため削除。

export function buildDocumentOverview(inputs: AnalysisInput): [string, Record<string, unknown>] {
  const documentFiles = [...inputs.documentFiles];
  const unsupportedFiles = documentFiles
    .filter(
      (file) => file.content.startsWith("[未対応") || file.content.startsWith("[PDF本文抽出には"),
    )
    .map((file) => file.path);
  const items = {
    document_uris: [...inputs.documentUris],
    document_file_paths: documentFiles.map((file) => file.path),
    unsupported_files: unsupportedFiles,
  };

  const lines = [
    "## ドキュメント事前抽出結果",
    "",
    `- 入力ドキュメントURI数: ${inputs.documentUris.length}`,
    `- 読み込み済み本文ファイル数: ${documentFiles.length}`,
    "",
    "### 入力ドキュメント",
    "",
    ...formatBullets(inputs.documentUris, "入力ドキュメントURIはありません。"),
    "",
    "### 本文抽出ファイル",
    "",
    ...formatDocumentTable(documentFiles),
  ];
  return [lines.join("\n"), items];
}

interface Dependency {
  kind: string;
  name: string;
  version: string;
  path: string;
}

function collectDependencies(files: Array<{ path: string; content: string }>): Dependency[] {
  const dependencies: Dependency[] = [];
  for (const file of files) {
    const name = path.basename(file.path).toLowerCase();
    if (name === "package.json") {
      dependencies.push(...dependenciesFromPackageJson(file));
    } else if (name === "requirements.txt") {
      dependencies.push(...dependenciesFromRequirements(file));
    } else if (name === "pyproject.toml") {
      dependencies.push(...dependenciesFromPyproject(file));
    } else if (name === "go.mod") {
      dependencies.push(...dependenciesFromGoMod(file));
    } else if (name === "gemfile") {
      dependencies.push(...dependenciesFromGemfile(file));
    }
  }
  return limitDicts(dependencies, 80);
}

function dependenciesFromPackageJson(file: { path: string; content: string }): Dependency[] {
  let payload: any;
  try {
    payload = JSON.parse(file.content);
  } catch {
    return [];
  }

  const dependencies: Dependency[] = [];
  for (const section of ["dependencies", "devDependencies"]) {
    const values = payload[section];
    if (values == null || typeof values !== "object" || Array.isArray(values)) {
      continue;
    }
    for (const [name, version] of Object.entries(values).sort(([left], [right]) =>
      left.localeCompare(right),
    )) {
      dependencies.push({
        kind: section,
        name: String(name),
        version: String(version),
        path: file.path,
      });
    }
  }
  return dependencies;
}

function dependenciesFromRequirements(file: { path: string; content: string }): Dependency[] {
  const dependencies: Dependency[] = [];
  for (const line of file.content.split(/\r?\n/)) {
    const stripped = line.trim();
    if (!stripped || stripped.startsWith("#") || stripped.startsWith("-")) {
      continue;
    }
    dependencies.push({
      kind: "python",
      name: dependencyName(stripped),
      version: stripped,
      path: file.path,
    });
  }
  return dependencies;
}

function dependenciesFromPyproject(file: { path: string; content: string }): Dependency[] {
  const dependencies: Dependency[] = [];
  let inDependencies = false;
  for (const line of file.content.split(/\r?\n/)) {
    const stripped = line.trim();
    if (stripped.startsWith("dependencies")) {
      inDependencies = stripped.includes("[") && !stripped.includes("]");
      dependencies.push(
        ...pyprojectDependencyEntries(
          [...stripped.matchAll(/"([^"]+)"/g)].map((match) => match[1]),
          file.path,
        ),
      );
      continue;
    }
    if (inDependencies) {
      if (stripped.startsWith("]")) {
        inDependencies = false;
        continue;
      }
      dependencies.push(
        ...pyprojectDependencyEntries(
          [...stripped.matchAll(/"([^"]+)"/g)].map((match) => match[1]),
          file.path,
        ),
      );
    }
  }
  return dependencies;
}

function pyprojectDependencyEntries(values: string[], filePath: string): Dependency[] {
  return values.map((value) => ({
    kind: "python",
    name: dependencyName(value),
    version: value,
    path: filePath,
  }));
}

function dependenciesFromGoMod(file: { path: string; content: string }): Dependency[] {
  const dependencies: Dependency[] = [];
  for (let line of file.content.split(/\r?\n/)) {
    line = line.trim();
    if (!line || line.startsWith("//")) {
      continue;
    }
    if (line.startsWith("require ")) {
      line = line.slice("require ".length).trim();
    }
    if (line === "(" || line === ")") {
      continue;
    }
    const parts = line.split(/\s+/);
    if (parts.length >= 2 && parts[0].includes(".")) {
      dependencies.push({
        kind: "go",
        name: parts[0],
        version: parts[1],
        path: file.path,
      });
    }
  }
  return dependencies;
}

function dependenciesFromGemfile(file: { path: string; content: string }): Dependency[] {
  return [...file.content.matchAll(/^\s*gem\s+['"]([^'"]+)['"](?:,\s*['"]([^'"]+)['"])?/gm)].map(
    (match) => ({
      kind: "ruby",
      name: match[1],
      version: match[2] || "",
      path: file.path,
    }),
  );
}

interface Route {
  method: string;
  path: string;
  source: string;
}

function collectApiRoutes(files: Array<{ path: string; content: string }>): Route[] {
  const routes: Route[] = [];
  for (const file of files) {
    if (isTestFile(file.path)) {
      continue;
    }
    routes.push(...routesFromContent(file));
    routes.push(...routesFromPath(file.path));
  }
  return limitDicts(routes, 80);
}

function routesFromContent(file: { path: string; content: string }): Route[] {
  const routes: Route[] = [];
  file.content.split(/\r?\n/).forEach((line, index) => {
    const lineNumber = index + 1;
    const stripped = line.trim();
    routes.push(...matchPythonRoute(file.path, lineNumber, stripped));
    routes.push(...matchFlaskRoute(file.path, lineNumber, stripped));
    routes.push(...matchExpressRoute(file.path, lineNumber, stripped));
    routes.push(...matchDjangoRoute(file.path, lineNumber, stripped));
    routes.push(...matchSpringRoute(file.path, lineNumber, stripped));
  });
  return routes;
}

function matchPythonRoute(filePath: string, lineNumber: number, line: string): Route[] {
  const match = line.match(
    /^@(?:\w+\.)?(?:app|router|api)\.(get|post|put|delete|patch|options|head)\(\s*['"]([^'"]+)['"]/,
  );
  return match ? [routeDict(match[1].toUpperCase(), match[2], filePath, lineNumber)] : [];
}

function matchFlaskRoute(filePath: string, lineNumber: number, line: string): Route[] {
  const match = line.match(/^@(?:\w+\.)?(?:app|bp|blueprint)\.route\(\s*['"]([^'"]+)['"]/);
  if (!match) {
    return [];
  }
  const methods = line.match(/methods\s*=\s*\[([^\]]+)\]/);
  if (!methods) {
    return [routeDict("GET", match[1], filePath, lineNumber)];
  }
  return [...methods[1].matchAll(/['"]([A-Za-z]+)['"]/g)].map((methodMatch) =>
    routeDict(methodMatch[1].toUpperCase(), match[1], filePath, lineNumber),
  );
}

function matchExpressRoute(filePath: string, lineNumber: number, line: string): Route[] {
  const match = line.match(
    /\b(?:app|router)\.(get|post|put|delete|patch|options|head|all|use)\(\s*[`'"]([^`'"]+)[`'"]/,
  );
  return match ? [routeDict(match[1].toUpperCase(), match[2], filePath, lineNumber)] : [];
}

function matchDjangoRoute(filePath: string, lineNumber: number, line: string): Route[] {
  const match = line.match(/\b(?:path|re_path)\(\s*['"]([^'"]+)['"]/);
  return match ? [routeDict("DJANGO", match[1], filePath, lineNumber)] : [];
}

function matchSpringRoute(filePath: string, lineNumber: number, line: string): Route[] {
  const match = line.match(
    /@(GetMapping|PostMapping|PutMapping|DeleteMapping|PatchMapping|RequestMapping)(?:\(\s*(?:value\s*=\s*)?['"]([^'"]+)['"])?/,
  );
  if (!match) {
    return [];
  }
  return [
    routeDict(
      match[1].replace("Mapping", "").toUpperCase() || "REQUEST",
      match[2] || "",
      filePath,
      lineNumber,
    ),
  ];
}

function routesFromPath(filePath: string): Route[] {
  const normalized = filePath.replaceAll("\\", "/");
  if (normalized.startsWith("pages/api/")) {
    return [
      routeDict(
        "NEXT_API",
        `/${removeExtension(normalized.slice("pages/api/".length))}`,
        filePath,
        0,
      ),
    ];
  }
  if (normalized.includes("/app/api/") && normalized.endsWith("/route.ts")) {
    const route = normalized.split("/app/api/", 2)[1].slice(0, -"/route.ts".length);
    return [routeDict("NEXT_API", `/${route}`, filePath, 0)];
  }
  return [];
}

interface DbDefinition {
  kind: string;
  name: string;
  path: string;
  line: string;
}

function collectDatabaseDefinitions(files: Array<{ path: string; content: string }>): DbDefinition[] {
  const definitions: DbDefinition[] = [];
  for (const file of files) {
    if (!isTestFile(file.path)) {
      definitions.push(...databaseDefinitionsFromContent(file));
    }
  }
  return limitDicts(definitions, 80);
}

function databaseDefinitionsFromContent(file: { path: string; content: string }): DbDefinition[] {
  const definitions: DbDefinition[] = [];
  file.content.split(/\r?\n/).forEach((line, index) => {
    const lineNumber = index + 1;
    const stripped = line.trim();
    const sqlMatch = stripped.match(
      /\b(CREATE\s+TABLE|ALTER\s+TABLE|CREATE\s+INDEX)\s+([^\s(]+)/i,
    );
    if (sqlMatch) {
      definitions.push({
        kind: sqlMatch[1].toUpperCase(),
        name: sqlMatch[2],
        path: file.path,
        line: String(lineNumber),
      });
    }

    const djangoMatch = stripped.match(/^class\s+(\w+)\((?:models\.)?Model\):/);
    if (djangoMatch) {
      definitions.push({
        kind: "Django model",
        name: djangoMatch[1],
        path: file.path,
        line: String(lineNumber),
      });
    }

    const prismaMatch = stripped.match(/^model\s+(\w+)\s+\{/);
    if (prismaMatch) {
      definitions.push({
        kind: "Prisma model",
        name: prismaMatch[1],
        path: file.path,
        line: String(lineNumber),
      });
    }
  });
  return definitions;
}

function dependencyName(requirement: string): string {
  return requirement.split(/\s*(?:==|>=|<=|~=|!=|>|<|\[)/, 1)[0].trim();
}

function routeDict(method: string, routePath: string, filePath: string, lineNumber: number): Route {
  return {
    method,
    path: routePath,
    source: sourceReference(filePath, lineNumber),
  };
}

function sourceReference(filePath: string, lineNumber: number): string {
  return lineNumber <= 0 ? filePath : `${filePath}:${lineNumber}`;
}

function isConfigFile(filePath: string): boolean {
  const name = path.basename(filePath).toLowerCase();
  const suffix = path.extname(filePath).toLowerCase();
  return (
    [
      ".env",
      ".env.example",
      "dockerfile",
      "package.json",
      "requirements.txt",
      "pyproject.toml",
      "go.mod",
      "gemfile",
      "composer.json",
      "pom.xml",
      "build.gradle",
    ].includes(name) || [".yaml", ".yml", ".toml", ".properties", ".conf"].includes(suffix)
  );
}

function isTestFile(filePath: string): boolean {
  const normalized = filePath.replaceAll("\\", "/").toLowerCase();
  const parts = normalized.split("/");
  const name = parts.at(-1) || "";
  return (
    parts.slice(0, -1).some((part) => ["test", "tests", "spec", "specs"].includes(part)) ||
    name.startsWith("test_") ||
    name.endsWith("_test.py") ||
    name.includes(".test.") ||
    name.includes(".spec.")
  );
}

function formatBullets(values: string[], empty: string): string[] {
  return values.length === 0 ? [empty] : values.map((value) => `- ${value}`);
}

function formatDependencyTable(dependencies: Dependency[]): string[] {
  if (dependencies.length === 0) {
    return ["依存関係候補は検出されませんでした。"];
  }
  return [
    "| 種別 | 名前 | バージョン/記述 | 根拠 |",
    "| --- | --- | --- | --- |",
    ...dependencies.map(
      (item) => `| ${item.kind} | ${item.name} | ${item.version} | ${item.path} |`,
    ),
  ];
}

function formatRouteTable(routes: Route[]): string[] {
  if (routes.length === 0) {
    return ["ルーティング/API候補は検出されませんでした。"];
  }
  return [
    "| メソッド | パス | 根拠 |",
    "| --- | --- | --- |",
    ...routes.map((item) => `| ${item.method} | ${item.path} | ${item.source} |`),
  ];
}

function formatDatabaseTable(definitions: DbDefinition[]): string[] {
  if (definitions.length === 0) {
    return ["DB定義/データモデル候補は検出されませんでした。"];
  }
  return [
    "| 種別 | 名前 | 根拠 |",
    "| --- | --- | --- |",
    ...definitions.map((item) => `| ${item.kind} | ${item.name} | ${item.path}:${item.line} |`),
  ];
}

function formatDocumentTable(files: Array<{ path: string; content: string }>): string[] {
  if (files.length === 0) {
    return ["本文抽出済みファイルはありません。"];
  }
  return [
    "| ファイル | 文字数 | 状態 |",
    "| --- | ---: | --- |",
    ...files.map(
      (file) => `| ${file.path} | ${file.content.length} | ${documentStatus(file)} |`,
    ),
  ];
}

function documentStatus(file: { content: string }): string {
  if (file.content.startsWith("[未対応")) {
    return "未対応形式";
  }
  if (file.content.startsWith("[PDF本文抽出には")) {
    return "PDF抽出依存不足";
  }
  if (file.content.startsWith("[") && file.content.includes("抽出できませんでした")) {
    return "抽出不可";
  }
  return "抽出済み";
}

function limitDicts<T>(items: T[], maxItems: number): T[] {
  return items.slice(0, maxItems);
}

function joinSections(...sections: string[]): string {
  return `${sections
    .map((section) => section.trim())
    .filter(Boolean)
    .join("\n\n")}\n`;
}

function removeExtension(value: string): string {
  const index = value.lastIndexOf(".");
  return index < 0 ? value : value.slice(0, index);
}
