import path from "node:path";
import { AnalysisTaskPayload } from "./payload.js";
import { AnalysisInput, SpecificationResult } from "./prompts.js";
import { GeminiClient } from "./gemini.js";
import {
  buildDocumentExtractionPrompt,
  buildDriftReportPrompt,
  buildSourceAnalysisPrompt,
  buildTrueDesignPrompt,
} from "./prompts.js";

export interface ExtractionResult extends SpecificationResult {
  extractedItems: Record<string, unknown>;
  debugArtifacts?: Record<string, string>;
}

export interface AnalysisEngine {
  extract(payload: AnalysisTaskPayload, inputs: AnalysisInput): Promise<ExtractionResult>;
}

export class PlaceholderSourceCodeAnalysisEngine implements AnalysisEngine {
  async extract(payload: AnalysisTaskPayload, inputs: AnalysisInput): Promise<ExtractionResult> {
    return {
      summary: "Source analysis engine placeholder. Gemini extraction is not implemented yet.",
      extractedItems: {
        source_archive_uri: inputs.sourceArchiveUri,
        known_document_count: inputs.documentUris.length,
        pending_extractors: [
          "file_structure",
          "api_routes",
          "database_definitions",
          "dependencies",
          "readme",
        ],
      },
    };
  }
}

export class GeminiSourceCodeAnalysisEngine implements AnalysisEngine {
  constructor(private geminiClient: GeminiClient) {}

  async extract(payload: AnalysisTaskPayload, inputs: AnalysisInput): Promise<ExtractionResult> {
    const [overviewMarkdown, overviewItems] = buildSourceCodeOverview(inputs);
    const prompt = buildSourceAnalysisPrompt(payload, inputs, overviewMarkdown);
    const response = await this.geminiClient.generate(prompt);
    const sourceCodeMapMarkdown = buildSourceCodeMapDocument(inputs);
    return {
      summary: joinSections(overviewMarkdown, `## Gemini抽出結果\n\n${response}`),
      extractedItems: {
        prompt_task: "SOURCE_ANALYSIS",
        source_archive_uri: inputs.sourceArchiveUri,
        source_file_count: inputs.sourceFiles.length,
        static_overview: overviewItems,
      },
      debugArtifacts: {
        "source-code-map.md": sourceCodeMapMarkdown,
      },
    };
  }
}

export class PlaceholderDocumentExtractionEngine implements AnalysisEngine {
  async extract(payload: AnalysisTaskPayload, inputs: AnalysisInput): Promise<ExtractionResult> {
    return {
      summary:
        "Document extraction engine placeholder. PDF/Excel extraction is not implemented yet.",
      extractedItems: {
        document_uris: [...inputs.documentUris],
        pending_extractors: ["pdf", "excel", "markdown", "plain_text"],
      },
    };
  }
}

export class GeminiDocumentExtractionEngine implements AnalysisEngine {
  constructor(private geminiClient: GeminiClient) {}

  async extract(payload: AnalysisTaskPayload, inputs: AnalysisInput): Promise<ExtractionResult> {
    const [overviewMarkdown, overviewItems] = buildDocumentOverview(inputs);
    const prompt = buildDocumentExtractionPrompt(payload, inputs, overviewMarkdown);
    const response = await this.geminiClient.generate(prompt);
    return {
      summary: joinSections(overviewMarkdown, `## Gemini抽出結果\n\n${response}`),
      extractedItems: {
        prompt_task: "DOCUMENT_EXTRACTION",
        document_count: inputs.documentUris.length,
        document_file_count: inputs.documentFiles.length,
        document_overview: overviewItems,
      },
    };
  }
}

export interface DesignGenerator {
  generate(
    payload: AnalysisTaskPayload,
    sourceSpecification: ExtractionResult,
    documentSpecification: ExtractionResult,
  ): Promise<string>;
}

export class PlaceholderTrueDesignGenerator implements DesignGenerator {
  async generate(
    payload: AnalysisTaskPayload,
    sourceSpecification: ExtractionResult,
    documentSpecification: ExtractionResult,
  ): Promise<string> {
    const title = payload.projectName || payload.jobId;
    return [
      "# True Design Document",
      "",
      "This is a placeholder artifact generated by the analysis worker skeleton.",
      "It must not be treated as the final implementation-derived design document.",
      "",
      "## Analysis Target",
      "",
      `- Project: ${title}`,
      `- Job ID: ${payload.jobId}`,
      `- Source archive: ${sourceSpecification.extractedItems.source_archive_uri}`,
      `- Existing documents: ${
        ((documentSpecification.extractedItems.document_uris as string[]) || []).length
      }`,
      "",
      "## Pending Implementation",
      "",
      "- F-02 source code analysis with Gemini API",
      "- F-03 document extraction with Gemini API",
      "- F-04 Markdown design document generation prompt",
      "",
    ].join("\n");
  }
}

export class GeminiTrueDesignGenerator implements DesignGenerator {
  constructor(private geminiClient: GeminiClient) {}

  async generate(
    payload: AnalysisTaskPayload,
    sourceSpecification: ExtractionResult,
    documentSpecification: ExtractionResult,
  ): Promise<string> {
    return this.geminiClient.generate(
      buildTrueDesignPrompt(payload, sourceSpecification, documentSpecification),
    );
  }
}

export class PlaceholderDriftReportGenerator implements DesignGenerator {
  async generate(): Promise<string> {
    return [
      "# Document Drift Report",
      "",
      "This is a placeholder artifact generated by the analysis worker skeleton.",
      "It must not be treated as the final drift analysis report.",
      "",
      "## Summary",
      "",
      "| Category | Count |",
      "| --- | ---: |",
      "| Implemented but undocumented | 0 |",
      "| Documented but not implemented | 0 |",
      "| Content mismatch | 0 |",
      "| Unknown | 0 |",
      "",
      "## Pending Implementation",
      "",
      "- F-05 comparison and four-category classification prompt",
      "",
    ].join("\n");
  }
}

export class GeminiDriftReportGenerator implements DesignGenerator {
  constructor(private geminiClient: GeminiClient) {}

  async generate(
    payload: AnalysisTaskPayload,
    sourceSpecification: ExtractionResult,
    documentSpecification: ExtractionResult,
  ): Promise<string> {
    return this.geminiClient.generate(
      buildDriftReportPrompt(payload, sourceSpecification, documentSpecification),
    );
  }
}

export function generatedArtifacts(trueDesignMarkdown: string, driftReportMarkdown: string) {
  return {
    trueDesignMarkdown,
    driftReportMarkdown,
    asFiles() {
      return {
        "true-design.md": this.trueDesignMarkdown,
        "document-drift-report.md": this.driftReportMarkdown,
      };
    },
  };
}

export function buildSourceCodeOverview(inputs: AnalysisInput): [string, Record<string, unknown>] {
  const filePaths = inputs.sourceFiles.map((file) => file.path);
  const dependencies = collectDependencies(inputs.sourceFiles);
  const apiRoutes = collectApiRoutes(inputs.sourceFiles);
  const databaseDefinitions = collectDatabaseDefinitions(inputs.sourceFiles);
  const configFiles = filePaths.filter((filePath) => isConfigFile(filePath));
  const readmeFiles = filePaths.filter((filePath) =>
    path.basename(filePath).toLowerCase().startsWith("readme"),
  );
  const directoryTree = buildDirectoryTree(filePaths);
  const moduleDependencyGraph = buildModuleDependencyGraph(inputs.sourceFiles);
  const iacStructureMap = buildIaCStructureMap(inputs.sourceFiles);

  const items = {
    file_structure: filePaths,
    dependencies,
    api_routes: apiRoutes,
    database_definitions: databaseDefinitions,
    config_files: configFiles,
    readme_files: readmeFiles,
  };

  const lines = [
    "## 静的構造解析結果",
    "",
    "### ディレクトリ構造",
    "",
    directoryTree || "ソースファイルはありません。",
    "",
    "### 設定ファイル",
    "",
    ...formatBullets(configFiles, "設定ファイル候補は検出されませんでした。"),
    "",
    "### README",
    "",
    ...formatBullets(readmeFiles, "README候補は検出されませんでした。"),
    "",
    "### 依存関係",
    "",
    ...formatDependencyTable(dependencies),
    "",
    "### ルーティング/API候補",
    "",
    ...formatRouteTable(apiRoutes),
    "",
    "### DB定義/データモデル候補",
    "",
    ...formatDatabaseTable(databaseDefinitions),
    "",
    "### モジュール間依存グラフ",
    "",
    moduleDependencyGraph,
    "",
    "### IaC構成要素",
    "",
    iacStructureMap,
  ];
  return [lines.join("\n"), items];
}

/**
 * ソースコードマップドキュメント（GCS保存用デバッグ成果物）を生成する。
 * ディレクトリツリー、モジュール依存グラフ、IaC構成要素を1ファイルにまとめる。
 */
export function buildSourceCodeMapDocument(inputs: AnalysisInput): string {
  const filePaths = inputs.sourceFiles.map((file) => file.path);
  const directoryTree = buildDirectoryTree(filePaths);
  const moduleDependencyGraph = buildModuleDependencyGraph(inputs.sourceFiles);
  const iacStructureMap = buildIaCStructureMap(inputs.sourceFiles);

  return [
    "# ソースコードマップ（静的解析結果）",
    "",
    "> このファイルは analysis-worker の静的解析フェーズで自動生成されたデバッグ用中間成果物です。",
    "> Gemini による解析結果ではなく、正規表現ベースの構造抽出結果を示します。",
    "",
    "---",
    "",
    "## 1. ディレクトリ構造",
    "",
    directoryTree || "ソースファイルはありません。",
    "",
    "---",
    "",
    "## 2. モジュール間依存グラフ",
    "",
    moduleDependencyGraph,
    "",
    "---",
    "",
    "## 3. IaC構成要素",
    "",
    iacStructureMap,
  ].join("\n");
}

/**
 * ファイルパス一覧からASCIIディレクトリツリーを生成する。
 *
 * @example
 * buildDirectoryTree(["src/index.ts", "src/engines.ts", "README.md"])
 * // => "README.md\nsrc/\n├── engines.ts\n└── index.ts"
 */
export function buildDirectoryTree(filePaths: string[]): string {
  if (filePaths.length === 0) {
    return "";
  }

  // パスをUnix区切りに正規化
  const normalized = filePaths.map((p) => p.replaceAll("\\", "/"));

  // ツリー構造をネストしたMapで構築: Map<name, subtree>
  type Tree = Map<string, Tree>;
  const root: Tree = new Map();

  for (const filePath of normalized) {
    const parts = filePath.split("/");
    let node = root;
    for (const part of parts) {
      if (!node.has(part)) {
        node.set(part, new Map());
      }
      node = node.get(part)!;
    }
  }

  function renderTree(node: Tree, prefix: string): string[] {
    const entries = [...node.entries()].sort(([a, aNode], [b, bNode]) => {
      // ディレクトリを先にソート
      const aIsDir = aNode.size > 0;
      const bIsDir = bNode.size > 0;
      if (aIsDir !== bIsDir) return aIsDir ? -1 : 1;
      return a.localeCompare(b);
    });
    const lines: string[] = [];
    entries.forEach(([name, subtree], index) => {
      const isLast = index === entries.length - 1;
      const connector = isLast ? "└── " : "├── ";
      const childPrefix = isLast ? prefix + "    " : prefix + "│   ";
      if (subtree.size > 0) {
        lines.push(`${prefix}${connector}${name}/`);
        lines.push(...renderTree(subtree, childPrefix));
      } else {
        lines.push(`${prefix}${connector}${name}`);
      }
    });
    return lines;
  }

  return renderTree(root, "").join("\n");
}

const MAX_DEPENDENCY_EDGES = 50;

/**
 * ソースファイルのimport文を静的解析し、Mermaid形式のモジュール依存グラフを生成する。
 * 相対パスimportのみを対象とし、外部パッケージは除外する。
 * 最大MAX_DEPENDENCY_EDGES件のエッジに制限する。
 */
export function buildModuleDependencyGraph(
  files: Array<{ path: string; content: string }>,
): string {
  const edges: Array<{ from: string; to: string }> = [];

  for (const file of files) {
    if (edges.length >= MAX_DEPENDENCY_EDGES) break;
    if (isTestFile(file.path)) continue;

    const ext = file.path.split(".").pop()?.toLowerCase() ?? "";
    const isJsTs = ["js", "jsx", "ts", "tsx", "mjs", "cjs"].includes(ext);
    const isPython = ext === "py";

    const importPaths: string[] = [];

    if (isJsTs) {
      // ES module: import ... from './foo'
      for (const match of file.content.matchAll(
        /^import\s+[\s\S]*?from\s+['"]([^'"]+)['"]/gm,
      )) {
        importPaths.push(match[1]);
      }
      // dynamic import: import('./foo') / require('./foo')
      for (const match of file.content.matchAll(
        /(?:import|require)\s*\(\s*['"]([^'"]+)['"]\s*\)/gm,
      )) {
        importPaths.push(match[1]);
      }
      // CommonJS: const x = require('./foo')
      for (const match of file.content.matchAll(
        /require\s*\(\s*['"]([^'"]+)['"]\s*\)/gm,
      )) {
        importPaths.push(match[1]);
      }
    }

    if (isPython) {
      // from .foo import bar
      for (const match of file.content.matchAll(
        /^from\s+(\.+[\w./]*)\s+import/gm,
      )) {
        importPaths.push(match[1]);
      }
      // import .foo  (relative import)
      for (const match of file.content.matchAll(/^import\s+(\.+[\w.]+)/gm)) {
        importPaths.push(match[1]);
      }
    }

    for (const importPath of importPaths) {
      // 相対パスのみ対象
      if (!importPath.startsWith(".")) continue;

      const fromDir = file.path.includes("/")
        ? file.path.slice(0, file.path.lastIndexOf("/"))
        : "";
      const resolvedRaw = fromDir ? `${fromDir}/${importPath}` : importPath;
      // 簡易パス正規化（../を解決）
      const resolved = resolveRelativePath(resolvedRaw);

      const fromLabel = sanitizeMermaidLabel(file.path);
      const toLabel = sanitizeMermaidLabel(resolved);
      if (fromLabel && toLabel && fromLabel !== toLabel) {
        edges.push({ from: fromLabel, to: toLabel });
      }
      if (edges.length >= MAX_DEPENDENCY_EDGES) break;
    }
  }

  if (edges.length === 0) {
    return "モジュール間の相対import依存は検出されませんでした。";
  }

  const truncated = edges.length >= MAX_DEPENDENCY_EDGES;
  const lines = [
    "```mermaid",
    "graph TD",
    ...edges.map((e) => `  ${JSON.stringify(e.from)} --> ${JSON.stringify(e.to)}`),
    "```",
  ];
  if (truncated) {
    lines.push("");
    lines.push(`> ※ エッジ数が上限（${MAX_DEPENDENCY_EDGES}件）に達したため、一部を省略しています。`);
  }
  return lines.join("\n");
}

/**
 * Terraformファイルを静的解析し、IaC構成要素をMarkdownテーブルで返す。
 */
export function buildIaCStructureMap(
  files: Array<{ path: string; content: string }>,
): string {
  interface IaCItem {
    kind: string;
    name: string;
    path: string;
  }
  const items: IaCItem[] = [];

  for (const file of files) {
    if (!file.path.endsWith(".tf")) continue;

    for (const line of file.content.split(/\r?\n/)) {
      const stripped = line.trim();

      // provider "aws" { / provider "google" {
      const providerMatch = stripped.match(/^provider\s+"([^"]+)"/);
      if (providerMatch) {
        items.push({ kind: "provider", name: providerMatch[1], path: file.path });
        continue;
      }

      // resource "google_cloud_run_service" "api" {
      const resourceMatch = stripped.match(/^resource\s+"([^"]+)"\s+"([^"]+)"/);
      if (resourceMatch) {
        items.push({
          kind: "resource",
          name: `${resourceMatch[1]}.${resourceMatch[2]}`,
          path: file.path,
        });
        continue;
      }

      // module "vpc" {
      const moduleMatch = stripped.match(/^module\s+"([^"]+)"/);
      if (moduleMatch) {
        items.push({ kind: "module", name: moduleMatch[1], path: file.path });
        continue;
      }

      // variable "project_id" {
      const variableMatch = stripped.match(/^variable\s+"([^"]+)"/);
      if (variableMatch) {
        items.push({ kind: "variable", name: variableMatch[1], path: file.path });
        continue;
      }

      // output "api_url" {
      const outputMatch = stripped.match(/^output\s+"([^"]+)"/);
      if (outputMatch) {
        items.push({ kind: "output", name: outputMatch[1], path: file.path });
        continue;
      }
    }
  }

  if (items.length === 0) {
    return "Terraformファイル（.tf）は検出されませんでした。";
  }

  return [
    "| 種別 | 名前 | ファイル |",
    "| --- | --- | --- |",
    ...items.map((item) => `| ${item.kind} | ${item.name} | ${item.path} |`),
  ].join("\n");
}

/**
 * 相対パスを簡易正規化する（../を解決）。
 */
function resolveRelativePath(rawPath: string): string {
  const parts = rawPath.split("/");
  const resolved: string[] = [];
  for (const part of parts) {
    if (part === "..") {
      resolved.pop();
    } else if (part !== ".") {
      resolved.push(part);
    }
  }
  return resolved.join("/");
}

/**
 * Mermaidラベルで使用できる文字列に変換する（特殊文字をエスケープ）。
 */
function sanitizeMermaidLabel(value: string): string {
  return value.trim();
}

export function buildDocumentOverview(inputs: AnalysisInput): [string, Record<string, unknown>] {
  const documentFiles = [...inputs.documentFiles];
  const unsupportedFiles = documentFiles
    .filter(
      (file) => file.content.startsWith("[未対応") || file.content.startsWith("[PDF本文抽出には"),
    )
    .map((file) => file.path);
  const items = {
    document_uris: [...inputs.documentUris],
    document_file_paths: documentFiles.map((file) => file.path),
    unsupported_files: unsupportedFiles,
  };

  const lines = [
    "## ドキュメント事前抽出結果",
    "",
    `- 入力ドキュメントURI数: ${inputs.documentUris.length}`,
    `- 読み込み済み本文ファイル数: ${documentFiles.length}`,
    "",
    "### 入力ドキュメント",
    "",
    ...formatBullets(inputs.documentUris, "入力ドキュメントURIはありません。"),
    "",
    "### 本文抽出ファイル",
    "",
    ...formatDocumentTable(documentFiles),
  ];
  return [lines.join("\n"), items];
}

interface Dependency {
  kind: string;
  name: string;
  version: string;
  path: string;
}

function collectDependencies(files: Array<{ path: string; content: string }>): Dependency[] {
  const dependencies: Dependency[] = [];
  for (const file of files) {
    const name = path.basename(file.path).toLowerCase();
    if (name === "package.json") {
      dependencies.push(...dependenciesFromPackageJson(file));
    } else if (name === "requirements.txt") {
      dependencies.push(...dependenciesFromRequirements(file));
    } else if (name === "pyproject.toml") {
      dependencies.push(...dependenciesFromPyproject(file));
    } else if (name === "go.mod") {
      dependencies.push(...dependenciesFromGoMod(file));
    } else if (name === "gemfile") {
      dependencies.push(...dependenciesFromGemfile(file));
    }
  }
  return limitDicts(dependencies, 80);
}

function dependenciesFromPackageJson(file: { path: string; content: string }): Dependency[] {
  let payload: any;
  try {
    payload = JSON.parse(file.content);
  } catch {
    return [];
  }

  const dependencies: Dependency[] = [];
  for (const section of ["dependencies", "devDependencies"]) {
    const values = payload[section];
    if (values == null || typeof values !== "object" || Array.isArray(values)) {
      continue;
    }
    for (const [name, version] of Object.entries(values).sort(([left], [right]) =>
      left.localeCompare(right),
    )) {
      dependencies.push({
        kind: section,
        name: String(name),
        version: String(version),
        path: file.path,
      });
    }
  }
  return dependencies;
}

function dependenciesFromRequirements(file: { path: string; content: string }): Dependency[] {
  const dependencies: Dependency[] = [];
  for (const line of file.content.split(/\r?\n/)) {
    const stripped = line.trim();
    if (!stripped || stripped.startsWith("#") || stripped.startsWith("-")) {
      continue;
    }
    dependencies.push({
      kind: "python",
      name: dependencyName(stripped),
      version: stripped,
      path: file.path,
    });
  }
  return dependencies;
}

function dependenciesFromPyproject(file: { path: string; content: string }): Dependency[] {
  const dependencies: Dependency[] = [];
  let inDependencies = false;
  for (const line of file.content.split(/\r?\n/)) {
    const stripped = line.trim();
    if (stripped.startsWith("dependencies")) {
      inDependencies = stripped.includes("[") && !stripped.includes("]");
      dependencies.push(
        ...pyprojectDependencyEntries(
          [...stripped.matchAll(/"([^"]+)"/g)].map((match) => match[1]),
          file.path,
        ),
      );
      continue;
    }
    if (inDependencies) {
      if (stripped.startsWith("]")) {
        inDependencies = false;
        continue;
      }
      dependencies.push(
        ...pyprojectDependencyEntries(
          [...stripped.matchAll(/"([^"]+)"/g)].map((match) => match[1]),
          file.path,
        ),
      );
    }
  }
  return dependencies;
}

function pyprojectDependencyEntries(values: string[], filePath: string): Dependency[] {
  return values.map((value) => ({
    kind: "python",
    name: dependencyName(value),
    version: value,
    path: filePath,
  }));
}

function dependenciesFromGoMod(file: { path: string; content: string }): Dependency[] {
  const dependencies: Dependency[] = [];
  for (let line of file.content.split(/\r?\n/)) {
    line = line.trim();
    if (!line || line.startsWith("//")) {
      continue;
    }
    if (line.startsWith("require ")) {
      line = line.slice("require ".length).trim();
    }
    if (line === "(" || line === ")") {
      continue;
    }
    const parts = line.split(/\s+/);
    if (parts.length >= 2 && parts[0].includes(".")) {
      dependencies.push({
        kind: "go",
        name: parts[0],
        version: parts[1],
        path: file.path,
      });
    }
  }
  return dependencies;
}

function dependenciesFromGemfile(file: { path: string; content: string }): Dependency[] {
  return [...file.content.matchAll(/^\s*gem\s+['"]([^'"]+)['"](?:,\s*['"]([^'"]+)['"])?/gm)].map(
    (match) => ({
      kind: "ruby",
      name: match[1],
      version: match[2] || "",
      path: file.path,
    }),
  );
}

interface Route {
  method: string;
  path: string;
  source: string;
}

function collectApiRoutes(files: Array<{ path: string; content: string }>): Route[] {
  const routes: Route[] = [];
  for (const file of files) {
    if (isTestFile(file.path)) {
      continue;
    }
    routes.push(...routesFromContent(file));
    routes.push(...routesFromPath(file.path));
  }
  return limitDicts(routes, 80);
}

function routesFromContent(file: { path: string; content: string }): Route[] {
  const routes: Route[] = [];
  file.content.split(/\r?\n/).forEach((line, index) => {
    const lineNumber = index + 1;
    const stripped = line.trim();
    routes.push(...matchPythonRoute(file.path, lineNumber, stripped));
    routes.push(...matchFlaskRoute(file.path, lineNumber, stripped));
    routes.push(...matchExpressRoute(file.path, lineNumber, stripped));
    routes.push(...matchDjangoRoute(file.path, lineNumber, stripped));
    routes.push(...matchSpringRoute(file.path, lineNumber, stripped));
  });
  return routes;
}

function matchPythonRoute(filePath: string, lineNumber: number, line: string): Route[] {
  const match = line.match(
    /^@(?:\w+\.)?(?:app|router|api)\.(get|post|put|delete|patch|options|head)\(\s*['"]([^'"]+)['"]/,
  );
  return match ? [routeDict(match[1].toUpperCase(), match[2], filePath, lineNumber)] : [];
}

function matchFlaskRoute(filePath: string, lineNumber: number, line: string): Route[] {
  const match = line.match(/^@(?:\w+\.)?(?:app|bp|blueprint)\.route\(\s*['"]([^'"]+)['"]/);
  if (!match) {
    return [];
  }
  const methods = line.match(/methods\s*=\s*\[([^\]]+)\]/);
  if (!methods) {
    return [routeDict("GET", match[1], filePath, lineNumber)];
  }
  return [...methods[1].matchAll(/['"]([A-Za-z]+)['"]/g)].map((methodMatch) =>
    routeDict(methodMatch[1].toUpperCase(), match[1], filePath, lineNumber),
  );
}

function matchExpressRoute(filePath: string, lineNumber: number, line: string): Route[] {
  const match = line.match(
    /\b(?:app|router)\.(get|post|put|delete|patch|options|head|all|use)\(\s*[`'"]([^`'"]+)[`'"]/,
  );
  return match ? [routeDict(match[1].toUpperCase(), match[2], filePath, lineNumber)] : [];
}

function matchDjangoRoute(filePath: string, lineNumber: number, line: string): Route[] {
  const match = line.match(/\b(?:path|re_path)\(\s*['"]([^'"]+)['"]/);
  return match ? [routeDict("DJANGO", match[1], filePath, lineNumber)] : [];
}

function matchSpringRoute(filePath: string, lineNumber: number, line: string): Route[] {
  const match = line.match(
    /@(GetMapping|PostMapping|PutMapping|DeleteMapping|PatchMapping|RequestMapping)(?:\(\s*(?:value\s*=\s*)?['"]([^'"]+)['"])?/,
  );
  if (!match) {
    return [];
  }
  return [
    routeDict(
      match[1].replace("Mapping", "").toUpperCase() || "REQUEST",
      match[2] || "",
      filePath,
      lineNumber,
    ),
  ];
}

function routesFromPath(filePath: string): Route[] {
  const normalized = filePath.replaceAll("\\", "/");
  if (normalized.startsWith("pages/api/")) {
    return [
      routeDict(
        "NEXT_API",
        `/${removeExtension(normalized.slice("pages/api/".length))}`,
        filePath,
        0,
      ),
    ];
  }
  if (normalized.includes("/app/api/") && normalized.endsWith("/route.ts")) {
    const route = normalized.split("/app/api/", 2)[1].slice(0, -"/route.ts".length);
    return [routeDict("NEXT_API", `/${route}`, filePath, 0)];
  }
  return [];
}

interface DbDefinition {
  kind: string;
  name: string;
  path: string;
  line: string;
}

function collectDatabaseDefinitions(files: Array<{ path: string; content: string }>): DbDefinition[] {
  const definitions: DbDefinition[] = [];
  for (const file of files) {
    if (!isTestFile(file.path)) {
      definitions.push(...databaseDefinitionsFromContent(file));
    }
  }
  return limitDicts(definitions, 80);
}

function databaseDefinitionsFromContent(file: { path: string; content: string }): DbDefinition[] {
  const definitions: DbDefinition[] = [];
  file.content.split(/\r?\n/).forEach((line, index) => {
    const lineNumber = index + 1;
    const stripped = line.trim();
    const sqlMatch = stripped.match(
      /\b(CREATE\s+TABLE|ALTER\s+TABLE|CREATE\s+INDEX)\s+([^\s(]+)/i,
    );
    if (sqlMatch) {
      definitions.push({
        kind: sqlMatch[1].toUpperCase(),
        name: sqlMatch[2],
        path: file.path,
        line: String(lineNumber),
      });
    }

    const djangoMatch = stripped.match(/^class\s+(\w+)\((?:models\.)?Model\):/);
    if (djangoMatch) {
      definitions.push({
        kind: "Django model",
        name: djangoMatch[1],
        path: file.path,
        line: String(lineNumber),
      });
    }

    const prismaMatch = stripped.match(/^model\s+(\w+)\s+\{/);
    if (prismaMatch) {
      definitions.push({
        kind: "Prisma model",
        name: prismaMatch[1],
        path: file.path,
        line: String(lineNumber),
      });
    }
  });
  return definitions;
}

function dependencyName(requirement: string): string {
  return requirement.split(/\s*(?:==|>=|<=|~=|!=|>|<|\[)/, 1)[0].trim();
}

function routeDict(method: string, routePath: string, filePath: string, lineNumber: number): Route {
  return {
    method,
    path: routePath,
    source: sourceReference(filePath, lineNumber),
  };
}

function sourceReference(filePath: string, lineNumber: number): string {
  return lineNumber <= 0 ? filePath : `${filePath}:${lineNumber}`;
}

function isConfigFile(filePath: string): boolean {
  const name = path.basename(filePath).toLowerCase();
  const suffix = path.extname(filePath).toLowerCase();
  return (
    [
      ".env",
      ".env.example",
      "dockerfile",
      "package.json",
      "requirements.txt",
      "pyproject.toml",
      "go.mod",
      "gemfile",
      "composer.json",
      "pom.xml",
      "build.gradle",
    ].includes(name) || [".yaml", ".yml", ".toml", ".properties", ".conf"].includes(suffix)
  );
}

function isTestFile(filePath: string): boolean {
  const normalized = filePath.replaceAll("\\", "/").toLowerCase();
  const parts = normalized.split("/");
  const name = parts.at(-1) || "";
  return (
    parts.slice(0, -1).some((part) => ["test", "tests", "spec", "specs"].includes(part)) ||
    name.startsWith("test_") ||
    name.endsWith("_test.py") ||
    name.includes(".test.") ||
    name.includes(".spec.")
  );
}

function formatBullets(values: string[], empty: string): string[] {
  return values.length === 0 ? [empty] : values.map((value) => `- ${value}`);
}

function formatDependencyTable(dependencies: Dependency[]): string[] {
  if (dependencies.length === 0) {
    return ["依存関係候補は検出されませんでした。"];
  }
  return [
    "| 種別 | 名前 | バージョン/記述 | 根拠 |",
    "| --- | --- | --- | --- |",
    ...dependencies.map(
      (item) => `| ${item.kind} | ${item.name} | ${item.version} | ${item.path} |`,
    ),
  ];
}

function formatRouteTable(routes: Route[]): string[] {
  if (routes.length === 0) {
    return ["ルーティング/API候補は検出されませんでした。"];
  }
  return [
    "| メソッド | パス | 根拠 |",
    "| --- | --- | --- |",
    ...routes.map((item) => `| ${item.method} | ${item.path} | ${item.source} |`),
  ];
}

function formatDatabaseTable(definitions: DbDefinition[]): string[] {
  if (definitions.length === 0) {
    return ["DB定義/データモデル候補は検出されませんでした。"];
  }
  return [
    "| 種別 | 名前 | 根拠 |",
    "| --- | --- | --- |",
    ...definitions.map((item) => `| ${item.kind} | ${item.name} | ${item.path}:${item.line} |`),
  ];
}

function formatDocumentTable(files: Array<{ path: string; content: string }>): string[] {
  if (files.length === 0) {
    return ["本文抽出済みファイルはありません。"];
  }
  return [
    "| ファイル | 文字数 | 状態 |",
    "| --- | ---: | --- |",
    ...files.map(
      (file) => `| ${file.path} | ${file.content.length} | ${documentStatus(file)} |`,
    ),
  ];
}

function documentStatus(file: { content: string }): string {
  if (file.content.startsWith("[未対応")) {
    return "未対応形式";
  }
  if (file.content.startsWith("[PDF本文抽出には")) {
    return "PDF抽出依存不足";
  }
  if (file.content.startsWith("[") && file.content.includes("抽出できませんでした")) {
    return "抽出不可";
  }
  return "抽出済み";
}

function limitDicts<T>(items: T[], maxItems: number): T[] {
  return items.slice(0, maxItems);
}

function joinSections(...sections: string[]): string {
  return `${sections
    .map((section) => section.trim())
    .filter(Boolean)
    .join("\n\n")}\n`;
}

function removeExtension(value: string): string {
  const index = value.lastIndexOf(".");
  return index < 0 ? value : value.slice(0, index);
}
